{"timestamp": "2017-09-11T10:57:50.264604Z", "level": "CRITICAL", "message": "Unhandled exception: %s", "system": "Darwin 15.6.0", "gh_handle": null, "command": "/usr/local/bin/gf config", "feature": "CONFIG", "type": "<class 'github.GithubException.UnknownObjectException'>", "value": "Exception: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3'}", "traceback": "File \"/usr/local/bin/gf\", line 11, in <module>\n    sys.exit(main())\n  File \"/usr/local/lib/python3.6/site-packages/gf/app_starter.py\", line 15, in main\n    app_controller.run()\n  File \"/usr/local/lib/python3.6/site-packages/gf/app_controller.py\", line 11, in run\n    task_check(get_command_argument())()\n  File \"/usr/local/lib/python3.6/site-packages/gf/app_controller.py\", line 35, in config_start\n    config_service.start()\n  File \"/usr/local/lib/python3.6/site-packages/gf/config/config_service.py\", line 13, in start\n    github.find_working_repo(credential)\n  File \"/usr/local/lib/python3.6/site-packages/external/web/github.py\", line 23, in find_working_repo\n    probably_repo = search_first_org_repo(repos)\n  File \"/usr/local/lib/python3.6/site-packages/external/web/github.py\", line 29, in search_first_org_repo\n    if is_org_repo(repo):\n  File \"/usr/local/lib/python3.6/site-packages/external/web/github.py\", line 39, in is_org_repo\n    return repo.organization is not None and \\\n  File \"/usr/local/lib/python3.6/site-packages/github/Repository.py\", line 476, in organization\n    self._completeIfNotSet(self._organization)\n  File \"/usr/local/lib/python3.6/site-packages/github/GithubObject.py\", line 251, in _completeIfNotSet\n    self._completeIfNeeded()\n  File \"/usr/local/lib/python3.6/site-packages/github/GithubObject.py\", line 255, in _completeIfNeeded\n    self.__complete()\n  File \"/usr/local/lib/python3.6/site-packages/github/GithubObject.py\", line 260, in __complete\n    self._url.value\n  File \"/usr/local/lib/python3.6/site-packages/github/Requester.py\", line 172, in requestJsonAndCheck\n    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))\n  File \"/usr/local/lib/python3.6/site-packages/github/Requester.py\", line 180, in __check\n    raise self.__createException(status, responseHeaders, output)"}
